### ISSUE TITLE
What bar are you using?

### ISSUE THREAD

**Issue by beyond9thousand** [niraj998/dotfiles#2]

**Comment by niraj998** [comment]
[eww bar](https://github.com/elkowar/eww.git)

**Comment by beyond9thousand** [comment]
oh i see, did you follow any tutorials or modify someone's existing config? i am trying to migrate from polybar but i have no experience creating eww bars etc

**Comment by niraj998** [comment]
no, I created all eww widgets and bar from scratch. 
you can find [documentation for creating your own here](https://elkowar.github.io/eww/eww.html)
you can use my config files or there are a lot of sample and example configs available on eww github repo itself for your reference

**Comment by beyond9thousand** [comment]
Thank you!
